# name: sese0

# on:  workflow_dispatch

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
             
#     - name: 推送
#       run: |
#           ls
#           sudo chmod +x aria2.sh
#           $GITHUB_WORKSPACE/aria2.sh
uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
with:
# ssh remote host
  host: 
# ssh remote port
  port: # optional, default is 22
  # ssh remote user
  user: 
  # content of ssh private key. ex raw content of ~/.ssh/id_rsa
  key: # optional
  # ssh remote password
  pass: # optional
  # connection timeout to remote host
  connect_timeout: # optional, default is 3s
  # execute pre-commands before scp
 first_ssh: # optional
  # scp from local to remote
  scp: # optional
  # execute post-commands after scp
  last_ssh: # optional
